# -- 코드를 입력하세요
# SELECT ANIMAL_ID, NAME, DATETIME
# FROM ANIMAL_INS
# WHERE NAME IN (
#     SELECT NAME
#     FROM ANIMAL_INS
#     GROUP BY NAME
#     HAVING COUNT(NAME) > 1
# )
# ORDER BY NAME ASC, DATETIME DESC;

SELECT ANIMAL_ID, NAME, DATETIME
FROM ANIMAL_INS
ORDER BY NAME ASC, DATETIME DESC;